### ISSUE TITLE
WebView Android not support file upload

### ISSUE THREAD

**Issue by Zinitter** [gin0606/cocos2dx-WebView#7]
There is no openFileChooser in WebView Android which allow user to choose file for upload in WebView.

WebView iOS is working properly for photo select and take photo with camera.

Tested with webpage :
http://www.anyimg.org/

Can you please help me on this Android issue?

Thanks.

**Comment by gin0606** [comment]
https://github.com/cocos2d/cocos2d-x/pull/7882#issuecomment-79882746

this repository is DEPRECATED.
please create issue to https://github.com/cocos2d/cocos2d-x
